build:
  version: "2.0"

accounts:
  message: "Welcome to VN Bank accounts related QA APIs "
  contactDetails:
    name: "Vikas Nishad- QA Lead"
    email: "vikas@vnbank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371