build:
  version: "1.0"

accounts:
  message: "Welcome to VN Bank accounts related prod APIs "
  contactDetails:
    name: "Vikas Nishad- Product Owner"
    email: "vikas@vnbank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384